<x-app>
    <main id="main" class="flex-1 dark:text-white">


        {{-- <div x-data="{bannerOpen: true}" x-show="bannerOpen" x-transition:enter="transition ease-out duration-300"
            class="relative flex border-outline bg-surface-alt p-4 text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark border-b">
            <p class="px-6 text-xs sm:text-sm text-pretty mx-auto">Limited Time Offer! Explore exclusive <a href="#"
                    class="font-medium text-primary underline-offset-2 hover:underline focus:underline focus:outline-hidden dark:text-primary-dark">deals
                    & savings</a> </p>
            <button class="absolute top-1/2 -translate-y-1/2 right-4 cursor-pointer hover:scale-125" aria-label="dismiss banner" title="Close" @click="bannerOpen = false">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true" stroke="currentColor"
                    fill="none" stroke-width="2.5" class="size-4 shrink-0">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
            </button>
        </div> --}}

        <h1 class="text-2xl font-bold mb-4">Dashboard</h1>
        <p>Welcome to your dashboard!</p>

        {{-- <a href="#" class="link-draw-in">Link Text</a> --}}

        {{-- <a href="https://spruecutters.com" class="btn-primary">Save</a>
        <a href="https://spruecutters.com" class="btn-secondary">Cancel</a>
        <a href="https://spruecutters.com" class="btn-danger">Delete</a> --}}

        {{-- <div class="mt-8 flex flex-col gap-8">
            <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-4">
                <article
                    class="group flex rounded-radius max-w-xs flex-col overflow-hidden border border-outline bg-surface-alt text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark">
                    <!-- Images -->
                    <div class="relative h-36">
                        <img src="https://penguinui.s3.amazonaws.com/component-assets/card-img-5.gif"
                            class="h-full w-full object-cover" alt="cover photo" />
                        <div
                            class="relative z-10 mx-auto -mt-14 size-28 overflow-hidden rounded-full border-4 border-surface-alt dark:border-surface-dark-alt">
                            <!-- The 3D avatar is generated by AI using https://perchance.org/ai-character-generator with the art style of 'Cute 3D Icon'. -->
                            <img src="https://penguinui.s3.amazonaws.com/component-assets/3d-avatar-1.webp"
                                class="h-full object-cover transition duration-700 ease-out group-hover:scale-105"
                                alt="avatar" />
                        </div>
                    </div>
                    <!-- Body -->
                    <div class="flex flex-col gap-2 p-6 text-center mt-12">
                        <h3 class="text-balance text-xl font-bold text-on-surface-strong lg:text-2xl dark:text-on-surface-dark-strong"
                            aria-describedby="profileDescription">Alice Brown</h3>
                        <span
                            class="mx-auto w-fit bg-primary px-2 py-1 text-xs text-on-primary dark:bg-primary-dark dark:text-on-primary-dark rounded-radius">UX
                            DESIGNER</span>
                        <p id="profileDescription" class="mt-4 text-pretty text-sm">
                            Making tech products user-friendly and delightful. Looking to
                            collaborate and create meaningful digital products.
                        </p>
                        <!-- Social Links -->
                        <div class="mt-4 flex items-center justify-center gap-6">
                            <!-- Email -->
                            <a href="mailto:youremailaddress@email.com"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="email">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                                    aria-hidden="true" class="size-7 shrink-0">
                                    <path
                                        d="M1.5 8.67v8.58a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3V8.67l-8.928 5.493a3 3 0 0 1-3.144 0L1.5 8.67Z" />
                                    <path
                                        d="M22.5 6.908V6.75a3 3 0 0 0-3-3h-15a3 3 0 0 0-3 3v.158l9.714 5.978a1.5 1.5 0 0 0 1.572 0L22.5 6.908Z" />
                                </svg>
                            </a>
                            <!-- Instagram -->
                            <a href="https://www.instagram.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="instagram">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-6 shrink-0">
                                    <path
                                        d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                                </svg>
                            </a>
                            <!-- X (Twitter) -->
                            <a href="https://www.x.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="x or twitter">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-5 shrink-0">
                                    <path
                                        d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" />
                                </svg>
                            </a>
                            <!-- Linkedin -->
                            <a href="https://www.linkedin.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="linkedin">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-6 shrink-0">
                                    <path
                                        d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" />
                                </svg>
                            </a>
                        </div>
                    </div>
                </article>
                <article
                    class="group flex rounded-radius max-w-xs flex-col overflow-hidden border border-outline bg-surface-alt text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark">
                    <!-- Images -->
                    <div class="relative h-36">
                        <img src="https://penguinui.s3.amazonaws.com/component-assets/card-img-5.gif"
                            class="h-full w-full object-cover" alt="cover photo" />
                        <div
                            class="relative z-10 mx-auto -mt-14 size-28 overflow-hidden rounded-full border-4 border-surface-alt dark:border-surface-dark-alt">
                            <!-- The 3D avatar is generated by AI using https://perchance.org/ai-character-generator with the art style of 'Cute 3D Icon'. -->
                            <img src="https://penguinui.s3.amazonaws.com/component-assets/3d-avatar-1.webp"
                                class="h-full object-cover transition duration-700 ease-out group-hover:scale-105"
                                alt="avatar" />
                        </div>
                    </div>
                    <!-- Body -->
                    <div class="flex flex-col gap-2 p-6 text-center mt-12">
                        <h3 class="text-balance text-xl font-bold text-on-surface-strong lg:text-2xl dark:text-on-surface-dark-strong"
                            aria-describedby="profileDescription">Alice Brown</h3>
                        <span
                            class="mx-auto w-fit bg-primary px-2 py-1 text-xs text-on-primary dark:bg-primary-dark dark:text-on-primary-dark rounded-radius">UX
                            DESIGNER</span>
                        <p id="profileDescription" class="mt-4 text-pretty text-sm">
                            Making tech products user-friendly and delightful. Looking to
                            collaborate and create meaningful digital products.
                        </p>
                        <!-- Social Links -->
                        <div class="mt-4 flex items-center justify-center gap-6">
                            <!-- Email -->
                            <a href="mailto:youremailaddress@email.com"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="email">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                                    aria-hidden="true" class="size-7 shrink-0">
                                    <path
                                        d="M1.5 8.67v8.58a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3V8.67l-8.928 5.493a3 3 0 0 1-3.144 0L1.5 8.67Z" />
                                    <path
                                        d="M22.5 6.908V6.75a3 3 0 0 0-3-3h-15a3 3 0 0 0-3 3v.158l9.714 5.978a1.5 1.5 0 0 0 1.572 0L22.5 6.908Z" />
                                </svg>
                            </a>
                            <!-- Instagram -->
                            <a href="https://www.instagram.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="instagram">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-6 shrink-0">
                                    <path
                                        d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                                </svg>
                            </a>
                            <!-- X (Twitter) -->
                            <a href="https://www.x.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="x or twitter">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-5 shrink-0">
                                    <path
                                        d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" />
                                </svg>
                            </a>
                            <!-- Linkedin -->
                            <a href="https://www.linkedin.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="linkedin">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-6 shrink-0">
                                    <path
                                        d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" />
                                </svg>
                            </a>
                        </div>
                    </div>
                </article>
                <article
                    class="group flex rounded-radius max-w-xs flex-col overflow-hidden border border-outline bg-surface-alt text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark">
                    <!-- Images -->
                    <div class="relative h-36">
                        <img src="https://penguinui.s3.amazonaws.com/component-assets/card-img-5.gif"
                            class="h-full w-full object-cover" alt="cover photo" />
                        <div
                            class="relative z-10 mx-auto -mt-14 size-28 overflow-hidden rounded-full border-4 border-surface-alt dark:border-surface-dark-alt">
                            <!-- The 3D avatar is generated by AI using https://perchance.org/ai-character-generator with the art style of 'Cute 3D Icon'. -->
                            <img src="https://penguinui.s3.amazonaws.com/component-assets/3d-avatar-1.webp"
                                class="h-full object-cover transition duration-700 ease-out group-hover:scale-105"
                                alt="avatar" />
                        </div>
                    </div>
                    <!-- Body -->
                    <div class="flex flex-col gap-2 p-6 text-center mt-12">
                        <h3 class="text-balance text-xl font-bold text-on-surface-strong lg:text-2xl dark:text-on-surface-dark-strong"
                            aria-describedby="profileDescription">Alice Brown</h3>
                        <span
                            class="mx-auto w-fit bg-primary px-2 py-1 text-xs text-on-primary dark:bg-primary-dark dark:text-on-primary-dark rounded-radius">UX
                            DESIGNER</span>
                        <p id="profileDescription" class="mt-4 text-pretty text-sm">
                            Making tech products user-friendly and delightful. Looking to
                            collaborate and create meaningful digital products.
                        </p>
                        <!-- Social Links -->
                        <div class="mt-4 flex items-center justify-center gap-6">
                            <!-- Email -->
                            <a href="mailto:youremailaddress@email.com"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="email">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                                    aria-hidden="true" class="size-7 shrink-0">
                                    <path
                                        d="M1.5 8.67v8.58a3 3 0 0 0 3 3h15a3 3 0 0 0 3-3V8.67l-8.928 5.493a3 3 0 0 1-3.144 0L1.5 8.67Z" />
                                    <path
                                        d="M22.5 6.908V6.75a3 3 0 0 0-3-3h-15a3 3 0 0 0-3 3v.158l9.714 5.978a1.5 1.5 0 0 0 1.572 0L22.5 6.908Z" />
                                </svg>
                            </a>
                            <!-- Instagram -->
                            <a href="https://www.instagram.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="instagram">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-6 shrink-0">
                                    <path
                                        d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334" />
                                </svg>
                            </a>
                            <!-- X (Twitter) -->
                            <a href="https://www.x.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="x or twitter">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-5 shrink-0">
                                    <path
                                        d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z" />
                                </svg>
                            </a>
                            <!-- Linkedin -->
                            <a href="https://www.linkedin.com" target="_blank"
                                class="text-on-surface hover:text-primary dark:text-on-surface-dark dark:hover:text-primary-dark"
                                aria-label="linkedin">
                                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                                    aria-hidden="true" class="size-6 shrink-0">
                                    <path
                                        d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z" />
                                </svg>
                            </a>
                        </div>
                    </div>
                </article>
            </div>

            <div
                class="overflow-hidden w-full overflow-x-auto rounded-radius border border-outline dark:border-outline-dark">
                <table class="w-full text-left text-sm text-on-surface dark:text-on-surface-dark">
                    <thead
                        class="border-b border-outline bg-surface-alt text-sm text-on-surface-strong dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark-strong">
                        <tr>
                            <th scope="col" class="p-4">CustomerID</th>
                            <th scope="col" class="p-4">Name</th>
                            <th scope="col" class="p-4">Email</th>
                            <th scope="col" class="p-4">Membership</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-outline dark:divide-outline-dark">
                        <tr>
                            <td class="p-4">2335</td>
                            <td class="p-4">Alice Brown</td>
                            <td class="p-4">alice.brown@gmail.com</td>
                            <td class="p-4"><button type="button"
                                    class="whitespace-nowrap rounded-radius bg-transparent p-0.5 font-semibold text-primary outline-primary hover:opacity-75 focus-visible:outline-2 focus-visible:outline-offset-2 active:opacity-100 active:outline-offset-0 dark:text-primary-dark dark:outline-primary-dark">Edit</button>
                            </td>
                        </tr>
                        <tr>
                            <td class="p-4">2338</td>
                            <td class="p-4">Bob Johnson</td>
                            <td class="p-4">johnson.bob@outlook.com</td>
                            <td class="p-4"><button type="button"
                                    class="whitespace-nowrap rounded-radius bg-transparent p-0.5 font-semibold text-primary outline-primary hover:opacity-75 focus-visible:outline-2 focus-visible:outline-offset-2 active:opacity-100 active:outline-offset-0 dark:text-primary-dark dark:outline-primary-dark">Edit</button>
                            </td>
                        </tr>
                        <tr>
                            <td class="p-4">2342</td>
                            <td class="p-4">Sarah Adams</td>
                            <td class="p-4">s.adams@gmail.com</td>
                            <td class="p-4"><button type="button"
                                    class="whitespace-nowrap rounded-radius bg-transparent p-0.5 font-semibold text-primary outline-primary hover:opacity-75 focus-visible:outline-2 focus-visible:outline-offset-2 active:opacity-100 active:outline-offset-0 dark:text-primary-dark dark:outline-primary-dark">Edit</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <article
                class="group grid rounded-radius max-w-2xl grid-cols-1 md:grid-cols-8 overflow-hidden border border-outline bg-surface-alt text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark">
                <!-- image -->
                <div class="col-span-3 overflow-hidden">
                    <img src="https://penguinui.s3.amazonaws.com/component-assets/card-img-4.webp"
                        class="h-52 md:h-full w-full object-cover transition duration-700 ease-out group-hover:scale-105"
                        alt="a men wearing VR goggles" />
                </div>
                <!-- body -->
                <div class="flex flex-col justify-center p-6 col-span-5">
                    <small class="mb-4 font-medium">Artificial Intelligence</small>
                    <h3 class="text-balance text-xl font-bold text-on-surface-strong lg:text-2xl dark:text-on-surface-dark-strong"
                        aria-describedby="articleDescription">AI made simple for SMEs
                        for Al</h3>
                    <p id="articleDescription" class="my-4 max-w-lg text-pretty text-sm">
                        Concierge-style scoping, fixed-price bundles, and vetted AI talent. Go from idea to impact in
                        2–4 weeks.
                    </p>
                    <a href="#"
                        class="w-fit font-medium text-primary underline-offset-2 hover:underline focus:underline focus:outline-hidden dark:text-primary-dark">
                        Read full story
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke="currentColor"
                            fill="none" stroke-width="2.5" aria-hidden="true" class="inline size-4">
                            <path stroke-linecap="round" stroke-linejoin="round"
                                d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" />
                        </svg>
                    </a>
                </div>
            </article>

            <article
                class="group rounded-radius flex max-w-md flex-col border border-outline bg-surface-alt p-6 text-on-surface dark:border-outline-dark dark:bg-surface-dark-alt dark:text-on-surface-dark">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill="currentColor"
                    class="size-12 text-on-surface-strong dark:text-on-surface-dark-strong group-hover:scale-105 transition duration-500 ease-out"
                    aria-hidden="true">
                    <path
                        d="M12 12a1 1 0 0 0 1-1V8.558a1 1 0 0 0-1-1h-1.388q0-.527.062-1.054.093-.558.31-.992t.559-.683q.34-.279.868-.279V3q-.868 0-1.52.372a3.3 3.3 0 0 0-1.085.992 4.9 4.9 0 0 0-.62 1.458A7.7 7.7 0 0 0 9 7.558V11a1 1 0 0 0 1 1zm-6 0a1 1 0 0 0 1-1V8.558a1 1 0 0 0-1-1H4.612q0-.527.062-1.054.094-.558.31-.992.217-.434.559-.683.34-.279.868-.279V3q-.868 0-1.52.372a3.3 3.3 0 0 0-1.085.992 4.9 4.9 0 0 0-.62 1.458A7.7 7.7 0 0 0 3 7.558V11a1 1 0 0 0 1 1z" />
                </svg>
                <p class="mt-2 text-pretty text-sm">
                    Simply put, this software transformed my workflow! Its intuitive
                    interface and powerful features make tasks a breeze. A game-changer
                    for productivity!
                </p>
                <!-- avatar & rating -->
                <div class="flex flex-col-reverse md:flex-row md:items-center mt-8 justify-between gap-6">
                    <!-- avatar & title -->
                    <div class="flex items-center gap-2">
                        <img src="https://penguinui.s3.amazonaws.com/component-assets/avatar-1.webp"
                            class="size-10 rounded-full object-cover" alt="avatar" />
                        <div class="flex flex-col gap-1">
                            <h3 class="font-bold leading-4 text-on-surface-strong dark:text-on-surface-dark-strong">Bob
                                Johnson</h3>
                            <span class="text-xs">CEO - TechNova</span>
                        </div>
                    </div>
                    <!-- Rating -->
                    <div class="flex items-center gap-1">
                        <span class="sr-only">Rated 4 stars</span>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="size-4 text-amber-500" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                                clip-rule="evenodd" />
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="size-4 text-amber-500" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                                clip-rule="evenodd" />
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="size-4 text-amber-500" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                                clip-rule="evenodd" />
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="size-4 text-amber-500" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                                clip-rule="evenodd" />
                        </svg>
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                            class="size-4 text-on-surface/50 dark:text-on-surface-dark/50" aria-hidden="true">
                            <path fill-rule="evenodd"
                                d="M10.788 3.21c.448-1.077 1.976-1.077 2.424 0l2.082 5.007 5.404.433c1.164.093 1.636 1.545.749 2.305l-4.117 3.527 1.257 5.273c.271 1.136-.964 2.033-1.96 1.425L12 18.354 7.373 21.18c-.996.608-2.231-.29-1.96-1.425l1.257-5.273-4.117-3.527c-.887-.76-.415-2.212.749-2.305l5.404-.433 2.082-5.006z"
                                clip-rule="evenodd" />
                        </svg>
                    </div>
                </div>
            </article>

            <div x-data="{ selectedTab: 'groups' }" class="w-full">
                <div x-on:keydown.right.prevent="$focus.wrap().next()"
                    x-on:keydown.left.prevent="$focus.wrap().previous()"
                    class="flex gap-2 overflow-x-auto border-b border-outline dark:border-outline-dark" role="tablist"
                    aria-label="tab options">
                    <button x-on:click="selectedTab = 'groups'" x-bind:aria-selected="selectedTab === 'groups'"
                        x-bind:tabindex="selectedTab === 'groups' ? '0' : '-1'"
                        x-bind:class="selectedTab === 'groups' ?
                            'font-bold text-primary border-b-2 border-primary dark:border-primary-dark dark:text-primary-dark' :
                            'text-on-surface font-medium dark:text-on-surface-dark dark:hover:border-b-outline-dark-strong dark:hover:text-on-surface-dark-strong hover:border-b-2 hover:border-b-outline-strong hover:text-on-surface-strong'"
                        class="h-min px-4 py-2 text-sm" type="button" role="tab"
                        aria-controls="tabpanelGroups">Groups</button>
                    <button x-on:click="selectedTab = 'likes'" x-bind:aria-selected="selectedTab === 'likes'"
                        x-bind:tabindex="selectedTab === 'likes' ? '0' : '-1'"
                        x-bind:class="selectedTab === 'likes' ?
                            'font-bold text-primary border-b-2 border-primary dark:border-primary-dark dark:text-primary-dark' :
                            'text-on-surface font-medium dark:text-on-surface-dark dark:hover:border-b-outline-dark-strong dark:hover:text-on-surface-dark-strong hover:border-b-2 hover:border-b-outline-strong hover:text-on-surface-strong'"
                        class="h-min px-4 py-2 text-sm" type="button" role="tab"
                        aria-controls="tabpanelLikes">Likes</button>
                    <button x-on:click="selectedTab = 'comments'" x-bind:aria-selected="selectedTab === 'comments'"
                        x-bind:tabindex="selectedTab === 'comments' ? '0' : '-1'"
                        x-bind:class="selectedTab === 'comments' ?
                            'font-bold text-primary border-b-2 border-primary dark:border-primary-dark dark:text-primary-dark' :
                            'text-on-surface font-medium dark:text-on-surface-dark dark:hover:border-b-outline-dark-strong dark:hover:text-on-surface-dark-strong hover:border-b-2 hover:border-b-outline-strong hover:text-on-surface-strong'"
                        class="h-min px-4 py-2 text-sm" type="button" role="tab"
                        aria-controls="tabpanelComments">Comments</button>
                    <button x-on:click="selectedTab = 'saved'" x-bind:aria-selected="selectedTab === 'saved'"
                        x-bind:tabindex="selectedTab === 'saved' ? '0' : '-1'"
                        x-bind:class="selectedTab === 'saved' ?
                            'font-bold text-primary border-b-2 border-primary dark:border-primary-dark dark:text-primary-dark' :
                            'text-on-surface font-medium dark:text-on-surface-dark dark:hover:border-b-outline-dark-strong dark:hover:text-on-surface-dark-strong hover:border-b-2 hover:border-b-outline-strong hover:text-on-surface-strong'"
                        class="h-min px-4 py-2 text-sm" type="button" role="tab"
                        aria-controls="tabpanelSaved">Saved</button>
                </div>
                <div class="px-2 py-4 text-on-surface dark:text-on-surface-dark">
                    <div x-cloak x-show="selectedTab === 'groups'" id="tabpanelGroups" role="tabpanel"
                        aria-label="groups"><b><a href="#" class="underline">Groups</a></b> tab is selected
                    </div>
                    <div x-cloak x-show="selectedTab === 'likes'" id="tabpanelLikes" role="tabpanel"
                        aria-label="likes"><b><a href="#" class="underline">Likes</a></b> tab is selected</div>
                    <div x-cloak x-show="selectedTab === 'comments'" id="tabpanelComments" role="tabpanel"
                        aria-label="comments"><b><a href="#" class="underline">Comments</a></b> tab is selected
                    </div>
                    <div x-cloak x-show="selectedTab === 'saved'" id="tabpanelSaved" role="tabpanel"
                        aria-label="saved"><b><a href="#" class="underline">Saved</a></b> tab is selected</div>
                </div>
            </div>

        </div> --}}
    </main>
</x-app>
